name: bring-it
description: Run `@bring-it/npm` in workflows

inputs:
  node-version:
    description: node-version of actions/setup-node
    required: true
    default: lts/*
  custom-command:
    description: Custom shell command
    required: false
  publish-command:
    description: Custom publish command
    default: na exec bring-it npm publish

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v6
      with:
        fetch-depth: 2

    - name: Setup node
      uses: actions/setup-node@v6
      with:
        node-version: ${{ inputs.node-version }}
        check-latest: true
        registry-url: https://registry.npmjs.org

    - name: Prepare corepack
      shell: bash
      run: |
        corepack disable npm
        corepack disable yarn
        corepack disable pnpm
        npm i -g npm@latest @antfu/ni corepack --force
        corepack enable npm
        corepack enable yarn
        corepack enable pnpm

    - name: Custom command
      shell: bash
      if: ${{ inputs.custom-command }}
      run: ${{ inputs.custom-command }}

    - name: Install
      shell: bash
      run: nci || ni || ni --force

    - name: Git config
      shell: bash
      run: git config core.filemode false

    - name: Test
      shell: bash
      run: nr test --if-present

    - name: Publish
      shell: bash
      run: ${{ inputs.publish-command }}
