packages:
  - packages/*

catalog:
  chalk: ^5.6.2
  cheetor: ^0.13.0
  es-toolkit: ^1.44.0
  execa: ^9.6.0
  globby: ^15.0.0
  ini: ^6.0.0
  lodash: ^4.17.21
  semver: ^7.7.3
  slash: ^5.1.0
  yargs: ^18.0.0

overrides:
  cpu-features: '-'

shamefullyHoist: true
