packages:
  - packages/*

catalog:
  chalk: ^5.4.1
  cheetor: ^0.13.0
  execa: ^9.6.0
  globby: ^14.1.0
  ini: ^5.0.0
  lodash: ^4.17.21
  semver: ^7.7.2
  slash: ^5.1.0
  yargs: ^18.0.0

overrides:
  cpu-features: '-'

shamefullyHoist: true
