name: bring-it

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Run
        uses: airkro/bring-it@actions
        with:
          npm-token: ${{ secrets.NPM_TOKEN }}
          publish-command: npx @bring-it/npm@0.2.10 npm
          custom-command: |
            cd packages
            mkdir -p sftp/dist
            touch $_/cli.mjs
            mkdir -p npm/dist
            touch $_/cli.mjs
            mkdir -p sample/dist
            touch $_/cli.mjs
