name: bring-it

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  test:
    strategy:
      matrix:
        os:
          - macos-latest
          - windows-latest
          - ubuntu-latest
        node:
          - lts/*
          - lts/-1
        exclude:
          - os: ubuntu-latest
            node: lts/*

    runs-on: ${{ matrix.os }}
    steps:
      - name: Run
        uses: airkro/bring-it@actions
        with:
          node-version: ${{ matrix.node }}

  publish:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Run
        uses: airkro/bring-it@actions
        with:
          npm-token: ${{ secrets.NPM_TOKEN }}
          publish-command: npx -p @bring-it/npm@latest bring-it npm
          custom-command: |
            cd packages
            mkdir -p cli/dist
            touch $_/cli.mjs
