name: bring-it

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Run
        uses: airkro/bring-it@actions
        with:
          npm-token: ${{ secrets.NPM_TOKEN }}
          publish-command: node packages/npm/lib/bin.mjs npm
          custom-command: |
            cd packages
            mkdir -p cli/dist
            touch $_/cli.mjs
            mkdir -p npm/dist
            touch $_/cli.mjs
